"""add Department

Revision ID: 857bade54883
Revises: 4e6d422dfdac
Create Date: 2025-06-14 20:53:59.574209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857bade54883'
down_revision = '4e6d422dfdac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
